env:
  browser: true
  es6: true
  mocha: true

plugins:
  - wdio

extends:
  - 'airbnb-base'
  - plugin:wdio/recommended
  
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  max-len: 0
  no-console: 0
  func-names: 0
  no-shadow: 0
  linebreak-style: 0
  camelcase: 0
  no-undef: 0
  no-return-assign: 0
  no-unused-expressions: 0